services:
  2fa-basic:
    build:
      context: ..
      dockerfile: examples/Dockerfile
      args:
        EXAMPLE: 2fa-basic
    ports:
      - '3000:3000'
    environment:
      PORT: 3000

  async-config:
    build:
      context: ..
      dockerfile: examples/Dockerfile
      args:
        EXAMPLE: async-config
    ports:
      - '3001:3001'
    environment:
      PORT: 3001

  hotp-counter:
    build:
      context: ..
      dockerfile: examples/Dockerfile
      args:
        EXAMPLE: hotp-counter
    ports:
      - '3002:3002'
    environment:
      PORT: 3002
